# Generated by Django 4.2.3 on 2024-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_img/')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=5000)),
                ('technology', models.CharField(max_length=100)),
                ('git_link', models.URLField(blank=True, max_length=100, null=True)),
                ('live_link', models.URLField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
