# Generated by Django 4.2.3 on 2024-02-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectsmodel_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectsModel',
            new_name='AllProjectsModel',
        ),
    ]
