# Generated by Django 4.2.3 on 2024-02-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_projectsmodel_allprojectsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProjectsModel',
            new_name='ProjectsModel',
        ),
    ]
