# Generated by Django 4.2.3 on 2024-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_allprojectsmodel_projectsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Adroid Development', 'Adroid Development'), ('Django Project ', 'Django Project'), ('Machine Learning', 'Machine Learning')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='descriptions',
            field=models.TextField(max_length=500),
        ),
    ]
