# Generated by Django 4.2.3 on 2024-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Phone_no', models.CharField(max_length=30)),
                ('Rating', models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('6', '⭐⭐⭐⭐⭐⭐'), ('7', '⭐⭐⭐⭐⭐⭐⭐')], max_length=7)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
