# Generated by Django 4.2.3 on 2024-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='Rating',
            field=models.IntegerField(choices=[('1', '★☆☆☆☆☆☆'), ('2', '★★☆☆☆☆☆'), ('3', '★★★☆☆☆☆'), ('4', '★★★★☆☆☆'), ('5', '★★★★★☆☆'), ('6', '★★★★★★☆'), ('7', '★★★★★★★')]),
        ),
    ]
