# Generated by Django 4.2.3 on 2024-02-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='Rating',
            field=models.CharField(choices=[('⭐️', '⭐️'), ('⭐️⭐️', '⭐️⭐️'), ('⭐️⭐️⭐️', '⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️⭐️⭐️⭐️')], max_length=14),
        ),
    ]
