# Generated by Django 4.2.3 on 2024-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_alter_skillmodel_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill/media/'),
        ),
    ]
